# Generated by Django 3.1.2 on 2020-11-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Ans',
            new_name='Answ',
        ),
    ]
